### ISSUE TITLE
Installation niggles

### ISSUE THREAD

**Issue by libbymiller** [andrewn/neue-radio#114]
Most of it works brilliantly, lovely job. And I love the initial list of links on the front of the external page.

A few small things when installing on the mac:
 * [install instructions](https://github.com/andrewn/neue-radio/blob/master/docs/INSTALL.md) need to say 'open up another window with localhost:5000' or similar
 * from localhost:5000, 'setup' does nothing on the Mac 'localhost 5020 cannot be reached'
 * from localhost:5000, clicking 'debug' link -> "Error: undefined"
 * Youtube app doesn't work with download ticked for me (maybe we could just remove that option?)

I can split these up into separare issues if you prefer.

**Comment by andrewn** [comment]
Separate issues would be 💯 if it's not too much trouble.

**Comment by libbymiller** [comment]
Split into #117 #118 #119
