### ISSUE TITLE
localhost:5000 on a mac - 'setup' link broken

### ISSUE THREAD

**Issue by libbymiller** [andrewn/neue-radio#118]
Front page - excellent idea - but on localhost:5000, 'setup' does nothing on the Mac  - get 'localhost 5020 cannot be reached'

ditto  'debug' link -> "Error: undefined"

**Comment by andrewn** [comment]
The Setup service manages files that `systemd` cares about so it doesn't make sense for it to work on the desktop with the current architecture. I guess we should hide the link or put a note in?

**Comment by pixelblend** [comment]
I'll add a note explaining that this is for a pi installation only

**Comment by pixelblend** [comment]
It was easier to remove them, in the end.
