### ISSUE TITLE
Issue with running JOBS=MAX npm install --production # use all cores

### ISSUE THREAD

**Issue by marklochrie50265** [andrewn/neue-radio#2]
npm ERR! git rev-list -n1 button-pulldown-support: fatal: ambiguous argument 'button-pulldown-support': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 button-pulldown-support: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 button-pulldown-support: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 button-pulldown-support: 
npm ERR! git rev-list -n1 button-pulldown-support: fatal: ambiguous argument 'button-pulldown-support': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 button-pulldown-support: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 button-pulldown-support: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 button-pulldown-support: 
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:andrewn/johnny-five.git /root/.npm/_git-remotes/git-github-com-andrewn-johnny-five-git-button-pulldown-support-709d3816: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-andrewn-johnny-five-git-button-pulldown-support-709d3816'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:andrewn/johnny-five.git /root/.npm/_git-remotes/git-github-com-andrewn-johnny-five-git-button-pulldown-support-709d3816: Permission denied (publickey).
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:andrewn/johnny-five.git /root/.npm/_git-remotes/git-github-com-andrewn-johnny-five-git-button-pulldown-support-709d3816: fatal: Could not read from remote repository.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:andrewn/johnny-five.git /root/.npm/_git-remotes/git-github-com-andrewn-johnny-five-git-button-pulldown-support-709d3816: 
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:andrewn/johnny-five.git /root/.npm/_git-remotes/git-github-com-andrewn-johnny-five-git-button-pulldown-support-709d3816: Please make sure you have the correct access rights
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:andrewn/johnny-five.git /root/.npm/_git-remotes/git-github-com-andrewn-johnny-five-git-button-pulldown-support-709d3816: and the repository exists.
npm ERR! Linux 4.4.38-v7+
npm ERR! argv "/opt/node/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:andrewn/johnny-five.git /root/.npm/_git-remotes/git-github-com-andrewn-johnny-five-git-button-pulldown-support-709d3816
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-andrewn-johnny-five-git-button-pulldown-support-709d3816'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/provision/rde/physical/npm-debug.log

**Comment by andrewn** [comment]
This has been fixed in the latest `package.json`
