### ISSUE TITLE
Pi3 b+ - need to set country to enable wifi

### ISSUE THREAD

**Issue by libbymiller** [andrewn/neue-radio#82]
For Install.md

There's no wifi until you do ```sudo raspi-config``` -> ````localisation options``` -> ```change wifi country```

**Comment by andrewn** [comment]
If you get a chance, it would be _very_ interesting to know if the following works:

Before booting the Pi, add `/Volumes/boot/wpa_supplicant.conf` with the following contents:

```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=DE

network={
  ssid="YOUR SSID"
  psk="YOUR PASSWORD"
  key_mgmt=WPA-PSK
}
```

The Pi will use this to connect to wi-fi. I'm just wondering if  `country=DE` is enough to contigure the wifi without going through `raspi-config`?

**Comment by libbymiller** [comment]
I'll definitely try it.

LIbby

**Comment by libbymiller** [comment]
so it doesn't seem to work on lite. Not investigated why yet.

**Comment by andrewn** [comment]
We could add a step to the provisioning script to set a country without
going through the GUI.

**Comment by libbymiller** [comment]
ok it just worked for me on lite, like this, i.e. with country first
```
country=GB
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
  ssid="YOUR SSID"
  psk="YOUR PASSWORD"
  key_mgmt=WPA-PSK
}
```

**Comment by andrewn** [comment]
Yep, having `country` first works for me on a Pi 3 B+ with Lite. Do you think this example config go in the INSTALL.md?

**Comment by libbymiller** [comment]
I just added it. Hope that's alright.
