### ISSUE TITLE
Missing installation instruction

### ISSUE THREAD

**Issue by libbymiller** [andrewn/neue-radio#83]
Sorry, minor thing
Install.md needs to include 

```sudo apt-get install git``` (if on lite) and
```git clone https://github.com/andrewn/neue-radio```

**Comment by pixelblend** [comment]
You can just download and run the provisioning from the internet, no prior installations required:

`curl https://raw.githubusercontent.com/andrewn/neue-radio/master/deployment/provision | sudo bash`

I'll update the docs to reflect this.
