### ISSUE TITLE
Uploading new apps via smb doesn't make them show up in http://raspberrypi.local:5020/

### ISSUE THREAD

**Issue by libbymiller** [andrewn/neue-radio#86]
I successfully connected to smb (that's brilliant!) and dragged the app directory into apps.

Then I should (I think) see it in http://raspberrypi.local:5020/ ? but it's not there (see screenshot). Reload and restart don't do anything.

<img width="764" alt="screen shot 2018-03-22 at 11 06 09" src="https://user-images.githubusercontent.com/210611/37767293-8b07c77c-2dc1-11e8-841a-389c20156ebf.png">
<img width="1194" alt="screen shot 2018-03-22 at 11 07 02" src="https://user-images.githubusercontent.com/210611/37767294-8b23fd98-2dc1-11e8-8495-514ff8cd45c8.png">

**Comment by andrewn** [comment]
I think this is a duplicate of #81.

**Comment by libbymiller** [comment]
Ah I assumed from the docs that it was implemented.
