### ISSUE TITLE
After copying over files via smb and rebooting, I don't get an install option

### ISSUE THREAD

**Issue by libbymiller** [andrewn/neue-radio#88]
Steps to reproduce:

* copy over peeps_and_cake to `apps` directory via SMB
* ssh in and reboot
* go to http://raspberrypi.local:5020/
* no install option (as suggested in docs)

<img width="1151" alt="screen shot 2018-03-22 at 13 44 41" src="https://user-images.githubusercontent.com/210611/37774104-3d681f38-2dd7-11e8-8fe8-f1f8e8585aa8.png">

**Comment by pixelblend** [comment]
The install option isnt dependent on any apps being added. Are you sure your repo is up to date?
