### ISSUE TITLE
`deployment/update` fails on `physical`, when installing on non-arm machine

### ISSUE THREAD

**Issue by pixelblend** [andrewn/neue-radio#91]
There’s a small issue where when you use `deployment/update` on a mac, it fails on the installation for this service, because it can’t install the `gpio`-based library.

Potential solution: [use a library](https://www.npmjs.com/package/npm-arch-dependencies) to allow architecture library installs.

**Comment by andrewn** [comment]
That library looks good. Maybe we can use [`scripts.postinstall`](https://docs.npmjs.com/misc/scripts) in NPM to automatically run `npm run archpm` on `npm install`.
