### ISSUE TITLE
Proposal: Bundle WebSocket code

### ISSUE THREAD

**Issue by andrewn** [andrewn/neue-radio#95]
I'm proposing we use [Rollup](https://rollupjs.org/) to bundle our shared WebSocket code for the browser and node.js. We've avoided this so far but it results in some limitations:

- can't use as ES6 module in the browser, which our apps use
- must include a script tag which forces the `createWebsocket` function name
- causes issues where Desktop Safari can't load the `createWebsocket` function
- `shared/websocket` code must all be in a single file

## node.js

```js
const createWebSocketOrWhatever = require('websocket');

const ws = createWebSocketOrWhatever();
```

## `script` tag

```js
<script src="/websocket"></script>
<script>
  const ws = createWebsocket(); // this name is globally exported
</script>
```

## ES Module

```js
<script type="module">
 import createWebSocketYouKnow from '/websocket/es.js'
 const ws = createWebSocketYouKnow();
</script>
```

The above would also be usable within a module:

```js
<script type="module">
 import createWebSocketYouKnow from '/websocket/es.js';
 const ws = createWebSocketYouKnow();
</script>
```

```js
// external.html
<script type="module">
 import main from './main.js';
 main();
</script>

// main.js
import createWebSocketYouKnow from '/websocket/es.js';
const ws = createWebSocketYouKnow();
```

The only sad thing is `/websocket/es.js`. I think we *could* have `/websocket/es` if we get express to serve it but it will have to be a different URL.

**Comment by pixelblend** [comment]
If we change [this line][1], would we be able to mount the `es.js` at `/weboscket`?

[1]:https://github.com/andrewn/neue-radio/blob/master/services/manager/lib/io/http/index.js#L49

**Comment by andrewn** [comment]
Good idea, we can map `es.js` as `/websocket`. 

In `shared/websocket/package.json` we could set `"main": "umd.js"` so that in node.js you will still `require('websocket');`
